# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  explorer-inmetro:
    external:
      name: onehost_nmiblocknet_default

services:
  explorerdb:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.inmetro.br
    hostname: explorerdb.inmetro.br
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      #- ./app/persistence/fabric/postgreSQL/db/createdb.sh:/docker-entrypoint-initdb.d/createdb.sh
      - ./createdb.sh:/docker-entrypoint-initdb.d/createdb.sh
      - pgdata:/var/lib/postgresql/data
    networks:
      - explorer-inmetro

  explorer:
    image: hyperledger/explorer:latest
    container_name: explorer.inmetro.br
    hostname: explorer.inmetro.br
    environment:
      - DATABASE_HOST=explorerdb.inmetro.br
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
      #- SSL_ENABLED=true
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./:/opt/explorer/app/platform/fabric/connection-profile
      - ../crypto-config:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    depends_on:
      explorerdb:
        condition: service_healthy
    #command: sh -c "sleep 16 && node /opt/explorer/main.js && tail -f /dev/null"
    ports:
      - 8080:8080
    networks:
      - explorer-inmetro
