version: '2'

volumes:
  orderer4.nmi:
  orderer5.nmi:
  peer0.nesa.br:


networks:
  nmiblocknet_default:

services:

  orderer4.nmi:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=10050
    container_name: orderer4.nmi
    networks:
    - nmiblocknet_default
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/nmi/orderers/orderer4.nmi/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/nmi/orderers/orderer4.nmi/tls/:/var/hyperledger/orderer/tls
        - orderer4.nmi:/var/hyperledger/production/orderer
    extra_hosts:
      - "peer0.inmetro.br:${INMETRO_IP_1}"
      - "orderer.nmi:${ORDERER_IP_1}"
      - "orderer2.nmi:${ORDERER_IP_1}"
      - "orderer3.nmi:${ORDERER_IP_1}"
    ports:
    - 10050:10050

  orderer5.nmi:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=11050
    container_name: orderer5.nmi
    networks:
    - nmiblocknet_default
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/nmi/orderers/orderer5.nmi/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/nmi/orderers/orderer5.nmi/tls/:/var/hyperledger/orderer/tls
        - orderer5.nmi:/var/hyperledger/production/orderer
    extra_hosts:
      - "peer0.inmetro.br:${INMETRO_IP_1}"
      - "orderer.nmi:${ORDERER_IP_1}"
      - "orderer2.nmi:${ORDERER_IP_1}"
      - "orderer3.nmi:${ORDERER_IP_1}"
    ports:
    - 11050:11050


      
  peer0.nesa.br:
    container_name: peer0.nesa.br
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.nesa.br
    networks:
      - nmiblocknet_default
    extra_hosts:
      - "peer0.inmetro.br:${INMETRO_IP_1}"
      - "orderer.nmi:${ORDERER_IP_1}"
      - "orderer2.nmi:${ORDERER_IP_1}"
      - "orderer3.nmi:${ORDERER_IP_1}"
    depends_on:
      - nesadb0
      
  nesadb0:
    container_name: nesadb0
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw    
    ports:
      - 5984:5984
    extra_hosts:
      - "peer0.inmetro.br:${INMETRO_IP_1}"
      - "orderer.nmi:${ORDERER_IP_1}"
      - "orderer2.nmi:${ORDERER_IP_1}"
      - "orderer3.nmi:${ORDERER_IP_1}"  
    networks:
      - nmiblocknet_default
      
      
  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    dns_search: .
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.nesa.br:9051
      - CORE_PEER_LOCALMSPID=NESAMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/nesa.br/peers/peer0.nesa.br/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/nesa.br/peers/peer0.nesa.br/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/nesa.br/peers/peer0.nesa.br/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/nesa.br/users/Admin@nesa.br/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/chain
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - peer0.nesa.br
    extra_hosts:
      - "peer0.inmetro.br:${INMETRO_IP_1}"
      - "orderer.nmi:${ORDERER_IP_1}"
      - "orderer2.nmi:${ORDERER_IP_1}"
      - "orderer3.nmi:${ORDERER_IP_1}"             
    networks:
      - nmiblocknet_default

